spring.application.name=fleet-manager

# Actuator & Observability
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

# Default Database Connection (Kubernetes Internal Service)
spring.datasource.url=jdbc:postgresql://fleet-db-service:5432/fleetdb
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
