spring.datasource.url=jdbc:postgresql://localhost:5432/fleetdb
spring.datasource.username=postgres
spring.datasource.password=password
# Hibernate will create tables for you
spring.jpa.hibernate.ddl-auto=update
